services:
  - type: web
    name: clubstonbury
    runtime: static
    buildCommand: npm install && node ./node_modules/.bin/vite build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /200.html
